# coding: utf-8

"""
    ConnexPay Reporting API

    REST API for retrieving reporting data. Currently Daily Accounting data only.

    The version of the OpenAPI document: v1
    Created by: https://docs.connexpay.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from connex_pay_python_sdk import schemas  # noqa: F401


class AuthenticationAcquireClientAuthorizationResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            guid = schemas.StrSchema
            status = schemas.StrSchema
            batchStatus = schemas.StrSchema
            timeStamp = schemas.StrSchema
            amount = schemas.IntSchema
            effectiveAmount = schemas.IntSchema
            orderNumber = schemas.StrSchema
            deviceGuid = schemas.StrSchema
            cardDataSource = schemas.StrSchema
            customerID = schemas.StrSchema
            batchGuid = schemas.StrSchema
            sendReceipt = schemas.BoolSchema
            allowCardEmv = schemas.BoolSchema
            processorStatusCode = schemas.StrSchema
            processorResponseMessage = schemas.StrSchema
            wasProcessed = schemas.BoolSchema
            authCode = schemas.StrSchema
            refNumber = schemas.StrSchema
            invoiceNumber = schemas.StrSchema
            customerReceipt = schemas.StrSchema
            statementDescription = schemas.StrSchema
        
            @staticmethod
            def enhancedData() -> typing.Type['AuthenticationAcquireClientAuthorizationResponseEnhancedData']:
                return AuthenticationAcquireClientAuthorizationResponseEnhancedData
        
            @staticmethod
            def card() -> typing.Type['AuthenticationAcquireClientAuthorizationResponseCard']:
                return AuthenticationAcquireClientAuthorizationResponseCard
            addressVerificationCode = schemas.StrSchema
            addressVerificationResult = schemas.StrSchema
            cvvVerificationCode = schemas.StrSchema
            cvvVerificationResult = schemas.StrSchema
        
            @staticmethod
            def riskResponse() -> typing.Type['AuthenticationAcquireClientAuthorizationResponseRiskResponse']:
                return AuthenticationAcquireClientAuthorizationResponseRiskResponse
            type = schemas.StrSchema
            __annotations__ = {
                "guid": guid,
                "status": status,
                "batchStatus": batchStatus,
                "timeStamp": timeStamp,
                "amount": amount,
                "effectiveAmount": effectiveAmount,
                "orderNumber": orderNumber,
                "deviceGuid": deviceGuid,
                "cardDataSource": cardDataSource,
                "customerID": customerID,
                "batchGuid": batchGuid,
                "sendReceipt": sendReceipt,
                "allowCardEmv": allowCardEmv,
                "processorStatusCode": processorStatusCode,
                "processorResponseMessage": processorResponseMessage,
                "wasProcessed": wasProcessed,
                "authCode": authCode,
                "refNumber": refNumber,
                "invoiceNumber": invoiceNumber,
                "customerReceipt": customerReceipt,
                "statementDescription": statementDescription,
                "enhancedData": enhancedData,
                "card": card,
                "addressVerificationCode": addressVerificationCode,
                "addressVerificationResult": addressVerificationResult,
                "cvvVerificationCode": cvvVerificationCode,
                "cvvVerificationResult": cvvVerificationResult,
                "riskResponse": riskResponse,
                "type": type,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["guid"]) -> MetaOapg.properties.guid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["batchStatus"]) -> MetaOapg.properties.batchStatus: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timeStamp"]) -> MetaOapg.properties.timeStamp: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["effectiveAmount"]) -> MetaOapg.properties.effectiveAmount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["orderNumber"]) -> MetaOapg.properties.orderNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["deviceGuid"]) -> MetaOapg.properties.deviceGuid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cardDataSource"]) -> MetaOapg.properties.cardDataSource: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["customerID"]) -> MetaOapg.properties.customerID: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["batchGuid"]) -> MetaOapg.properties.batchGuid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sendReceipt"]) -> MetaOapg.properties.sendReceipt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["allowCardEmv"]) -> MetaOapg.properties.allowCardEmv: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["processorStatusCode"]) -> MetaOapg.properties.processorStatusCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["processorResponseMessage"]) -> MetaOapg.properties.processorResponseMessage: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["wasProcessed"]) -> MetaOapg.properties.wasProcessed: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["authCode"]) -> MetaOapg.properties.authCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["refNumber"]) -> MetaOapg.properties.refNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["invoiceNumber"]) -> MetaOapg.properties.invoiceNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["customerReceipt"]) -> MetaOapg.properties.customerReceipt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["statementDescription"]) -> MetaOapg.properties.statementDescription: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["enhancedData"]) -> 'AuthenticationAcquireClientAuthorizationResponseEnhancedData': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["card"]) -> 'AuthenticationAcquireClientAuthorizationResponseCard': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["addressVerificationCode"]) -> MetaOapg.properties.addressVerificationCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["addressVerificationResult"]) -> MetaOapg.properties.addressVerificationResult: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cvvVerificationCode"]) -> MetaOapg.properties.cvvVerificationCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cvvVerificationResult"]) -> MetaOapg.properties.cvvVerificationResult: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["riskResponse"]) -> 'AuthenticationAcquireClientAuthorizationResponseRiskResponse': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["guid", "status", "batchStatus", "timeStamp", "amount", "effectiveAmount", "orderNumber", "deviceGuid", "cardDataSource", "customerID", "batchGuid", "sendReceipt", "allowCardEmv", "processorStatusCode", "processorResponseMessage", "wasProcessed", "authCode", "refNumber", "invoiceNumber", "customerReceipt", "statementDescription", "enhancedData", "card", "addressVerificationCode", "addressVerificationResult", "cvvVerificationCode", "cvvVerificationResult", "riskResponse", "type", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["guid"]) -> typing.Union[MetaOapg.properties.guid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["batchStatus"]) -> typing.Union[MetaOapg.properties.batchStatus, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timeStamp"]) -> typing.Union[MetaOapg.properties.timeStamp, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amount"]) -> typing.Union[MetaOapg.properties.amount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["effectiveAmount"]) -> typing.Union[MetaOapg.properties.effectiveAmount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["orderNumber"]) -> typing.Union[MetaOapg.properties.orderNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["deviceGuid"]) -> typing.Union[MetaOapg.properties.deviceGuid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cardDataSource"]) -> typing.Union[MetaOapg.properties.cardDataSource, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["customerID"]) -> typing.Union[MetaOapg.properties.customerID, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["batchGuid"]) -> typing.Union[MetaOapg.properties.batchGuid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sendReceipt"]) -> typing.Union[MetaOapg.properties.sendReceipt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["allowCardEmv"]) -> typing.Union[MetaOapg.properties.allowCardEmv, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["processorStatusCode"]) -> typing.Union[MetaOapg.properties.processorStatusCode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["processorResponseMessage"]) -> typing.Union[MetaOapg.properties.processorResponseMessage, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["wasProcessed"]) -> typing.Union[MetaOapg.properties.wasProcessed, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["authCode"]) -> typing.Union[MetaOapg.properties.authCode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["refNumber"]) -> typing.Union[MetaOapg.properties.refNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["invoiceNumber"]) -> typing.Union[MetaOapg.properties.invoiceNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["customerReceipt"]) -> typing.Union[MetaOapg.properties.customerReceipt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["statementDescription"]) -> typing.Union[MetaOapg.properties.statementDescription, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["enhancedData"]) -> typing.Union['AuthenticationAcquireClientAuthorizationResponseEnhancedData', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["card"]) -> typing.Union['AuthenticationAcquireClientAuthorizationResponseCard', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["addressVerificationCode"]) -> typing.Union[MetaOapg.properties.addressVerificationCode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["addressVerificationResult"]) -> typing.Union[MetaOapg.properties.addressVerificationResult, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cvvVerificationCode"]) -> typing.Union[MetaOapg.properties.cvvVerificationCode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cvvVerificationResult"]) -> typing.Union[MetaOapg.properties.cvvVerificationResult, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["riskResponse"]) -> typing.Union['AuthenticationAcquireClientAuthorizationResponseRiskResponse', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> typing.Union[MetaOapg.properties.type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["guid", "status", "batchStatus", "timeStamp", "amount", "effectiveAmount", "orderNumber", "deviceGuid", "cardDataSource", "customerID", "batchGuid", "sendReceipt", "allowCardEmv", "processorStatusCode", "processorResponseMessage", "wasProcessed", "authCode", "refNumber", "invoiceNumber", "customerReceipt", "statementDescription", "enhancedData", "card", "addressVerificationCode", "addressVerificationResult", "cvvVerificationCode", "cvvVerificationResult", "riskResponse", "type", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        guid: typing.Union[MetaOapg.properties.guid, str, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        batchStatus: typing.Union[MetaOapg.properties.batchStatus, str, schemas.Unset] = schemas.unset,
        timeStamp: typing.Union[MetaOapg.properties.timeStamp, str, schemas.Unset] = schemas.unset,
        amount: typing.Union[MetaOapg.properties.amount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        effectiveAmount: typing.Union[MetaOapg.properties.effectiveAmount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        orderNumber: typing.Union[MetaOapg.properties.orderNumber, str, schemas.Unset] = schemas.unset,
        deviceGuid: typing.Union[MetaOapg.properties.deviceGuid, str, schemas.Unset] = schemas.unset,
        cardDataSource: typing.Union[MetaOapg.properties.cardDataSource, str, schemas.Unset] = schemas.unset,
        customerID: typing.Union[MetaOapg.properties.customerID, str, schemas.Unset] = schemas.unset,
        batchGuid: typing.Union[MetaOapg.properties.batchGuid, str, schemas.Unset] = schemas.unset,
        sendReceipt: typing.Union[MetaOapg.properties.sendReceipt, bool, schemas.Unset] = schemas.unset,
        allowCardEmv: typing.Union[MetaOapg.properties.allowCardEmv, bool, schemas.Unset] = schemas.unset,
        processorStatusCode: typing.Union[MetaOapg.properties.processorStatusCode, str, schemas.Unset] = schemas.unset,
        processorResponseMessage: typing.Union[MetaOapg.properties.processorResponseMessage, str, schemas.Unset] = schemas.unset,
        wasProcessed: typing.Union[MetaOapg.properties.wasProcessed, bool, schemas.Unset] = schemas.unset,
        authCode: typing.Union[MetaOapg.properties.authCode, str, schemas.Unset] = schemas.unset,
        refNumber: typing.Union[MetaOapg.properties.refNumber, str, schemas.Unset] = schemas.unset,
        invoiceNumber: typing.Union[MetaOapg.properties.invoiceNumber, str, schemas.Unset] = schemas.unset,
        customerReceipt: typing.Union[MetaOapg.properties.customerReceipt, str, schemas.Unset] = schemas.unset,
        statementDescription: typing.Union[MetaOapg.properties.statementDescription, str, schemas.Unset] = schemas.unset,
        enhancedData: typing.Union['AuthenticationAcquireClientAuthorizationResponseEnhancedData', schemas.Unset] = schemas.unset,
        card: typing.Union['AuthenticationAcquireClientAuthorizationResponseCard', schemas.Unset] = schemas.unset,
        addressVerificationCode: typing.Union[MetaOapg.properties.addressVerificationCode, str, schemas.Unset] = schemas.unset,
        addressVerificationResult: typing.Union[MetaOapg.properties.addressVerificationResult, str, schemas.Unset] = schemas.unset,
        cvvVerificationCode: typing.Union[MetaOapg.properties.cvvVerificationCode, str, schemas.Unset] = schemas.unset,
        cvvVerificationResult: typing.Union[MetaOapg.properties.cvvVerificationResult, str, schemas.Unset] = schemas.unset,
        riskResponse: typing.Union['AuthenticationAcquireClientAuthorizationResponseRiskResponse', schemas.Unset] = schemas.unset,
        type: typing.Union[MetaOapg.properties.type, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AuthenticationAcquireClientAuthorizationResponse':
        return super().__new__(
            cls,
            *args,
            guid=guid,
            status=status,
            batchStatus=batchStatus,
            timeStamp=timeStamp,
            amount=amount,
            effectiveAmount=effectiveAmount,
            orderNumber=orderNumber,
            deviceGuid=deviceGuid,
            cardDataSource=cardDataSource,
            customerID=customerID,
            batchGuid=batchGuid,
            sendReceipt=sendReceipt,
            allowCardEmv=allowCardEmv,
            processorStatusCode=processorStatusCode,
            processorResponseMessage=processorResponseMessage,
            wasProcessed=wasProcessed,
            authCode=authCode,
            refNumber=refNumber,
            invoiceNumber=invoiceNumber,
            customerReceipt=customerReceipt,
            statementDescription=statementDescription,
            enhancedData=enhancedData,
            card=card,
            addressVerificationCode=addressVerificationCode,
            addressVerificationResult=addressVerificationResult,
            cvvVerificationCode=cvvVerificationCode,
            cvvVerificationResult=cvvVerificationResult,
            riskResponse=riskResponse,
            type=type,
            _configuration=_configuration,
            **kwargs,
        )

from connex_pay_python_sdk.model.authentication_acquire_client_authorization_response_card import AuthenticationAcquireClientAuthorizationResponseCard
from connex_pay_python_sdk.model.authentication_acquire_client_authorization_response_enhanced_data import AuthenticationAcquireClientAuthorizationResponseEnhancedData
from connex_pay_python_sdk.model.authentication_acquire_client_authorization_response_risk_response import AuthenticationAcquireClientAuthorizationResponseRiskResponse
