# coding: utf-8

"""
    ConnexPay Reporting API

    REST API for retrieving reporting data. Currently Daily Accounting data only.

    The version of the OpenAPI document: v1
    Created by: https://docs.connexpay.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from connex_pay_python_sdk import schemas  # noqa: F401


class CancellationEntireTripCancellationRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "DeviceGuid",
            "SaleGuid",
        }
        
        class properties:
            DeviceGuid = schemas.StrSchema
            SaleGuid = schemas.StrSchema
            SequenceNumber = schemas.StrSchema
            VoidReason = schemas.StrSchema
            __annotations__ = {
                "DeviceGuid": DeviceGuid,
                "SaleGuid": SaleGuid,
                "SequenceNumber": SequenceNumber,
                "VoidReason": VoidReason,
            }
    
    DeviceGuid: MetaOapg.properties.DeviceGuid
    SaleGuid: MetaOapg.properties.SaleGuid
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["DeviceGuid"]) -> MetaOapg.properties.DeviceGuid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["SaleGuid"]) -> MetaOapg.properties.SaleGuid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["SequenceNumber"]) -> MetaOapg.properties.SequenceNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["VoidReason"]) -> MetaOapg.properties.VoidReason: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["DeviceGuid", "SaleGuid", "SequenceNumber", "VoidReason", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["DeviceGuid"]) -> MetaOapg.properties.DeviceGuid: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["SaleGuid"]) -> MetaOapg.properties.SaleGuid: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["SequenceNumber"]) -> typing.Union[MetaOapg.properties.SequenceNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["VoidReason"]) -> typing.Union[MetaOapg.properties.VoidReason, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["DeviceGuid", "SaleGuid", "SequenceNumber", "VoidReason", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        DeviceGuid: typing.Union[MetaOapg.properties.DeviceGuid, str, ],
        SaleGuid: typing.Union[MetaOapg.properties.SaleGuid, str, ],
        SequenceNumber: typing.Union[MetaOapg.properties.SequenceNumber, str, schemas.Unset] = schemas.unset,
        VoidReason: typing.Union[MetaOapg.properties.VoidReason, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CancellationEntireTripCancellationRequest':
        return super().__new__(
            cls,
            *args,
            DeviceGuid=DeviceGuid,
            SaleGuid=SaleGuid,
            SequenceNumber=SequenceNumber,
            VoidReason=VoidReason,
            _configuration=_configuration,
            **kwargs,
        )
