# coding: utf-8

"""
    ConnexPay Reporting API

    REST API for retrieving reporting data. Currently Daily Accounting data only.

    The version of the OpenAPI document: v1
    Created by: https://docs.connexpay.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from connex_pay_python_sdk import schemas  # noqa: F401


class CardCancelVirtualCardResponseCard(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            cardGuid = schemas.StrSchema
            amountLimit = schemas.NumberSchema
            usageLimit = schemas.IntSchema
            limitWindow = schemas.StrSchema
            expirationDate = schemas.StrSchema
            expiration = schemas.StrSchema
            firstSix = schemas.StrSchema
            lastFour = schemas.StrSchema
            nameLine1 = schemas.StrSchema
            nameLine2 = schemas.StrSchema
            status = schemas.StrSchema
            cardType = schemas.StrSchema
            __annotations__ = {
                "cardGuid": cardGuid,
                "amountLimit": amountLimit,
                "usageLimit": usageLimit,
                "limitWindow": limitWindow,
                "expirationDate": expirationDate,
                "expiration": expiration,
                "firstSix": firstSix,
                "lastFour": lastFour,
                "nameLine1": nameLine1,
                "nameLine2": nameLine2,
                "status": status,
                "cardType": cardType,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cardGuid"]) -> MetaOapg.properties.cardGuid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amountLimit"]) -> MetaOapg.properties.amountLimit: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["usageLimit"]) -> MetaOapg.properties.usageLimit: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["limitWindow"]) -> MetaOapg.properties.limitWindow: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expirationDate"]) -> MetaOapg.properties.expirationDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expiration"]) -> MetaOapg.properties.expiration: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["firstSix"]) -> MetaOapg.properties.firstSix: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["lastFour"]) -> MetaOapg.properties.lastFour: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["nameLine1"]) -> MetaOapg.properties.nameLine1: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["nameLine2"]) -> MetaOapg.properties.nameLine2: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cardType"]) -> MetaOapg.properties.cardType: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["cardGuid", "amountLimit", "usageLimit", "limitWindow", "expirationDate", "expiration", "firstSix", "lastFour", "nameLine1", "nameLine2", "status", "cardType", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cardGuid"]) -> typing.Union[MetaOapg.properties.cardGuid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amountLimit"]) -> typing.Union[MetaOapg.properties.amountLimit, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["usageLimit"]) -> typing.Union[MetaOapg.properties.usageLimit, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["limitWindow"]) -> typing.Union[MetaOapg.properties.limitWindow, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expirationDate"]) -> typing.Union[MetaOapg.properties.expirationDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expiration"]) -> typing.Union[MetaOapg.properties.expiration, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["firstSix"]) -> typing.Union[MetaOapg.properties.firstSix, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["lastFour"]) -> typing.Union[MetaOapg.properties.lastFour, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["nameLine1"]) -> typing.Union[MetaOapg.properties.nameLine1, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["nameLine2"]) -> typing.Union[MetaOapg.properties.nameLine2, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cardType"]) -> typing.Union[MetaOapg.properties.cardType, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["cardGuid", "amountLimit", "usageLimit", "limitWindow", "expirationDate", "expiration", "firstSix", "lastFour", "nameLine1", "nameLine2", "status", "cardType", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        cardGuid: typing.Union[MetaOapg.properties.cardGuid, str, schemas.Unset] = schemas.unset,
        amountLimit: typing.Union[MetaOapg.properties.amountLimit, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        usageLimit: typing.Union[MetaOapg.properties.usageLimit, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        limitWindow: typing.Union[MetaOapg.properties.limitWindow, str, schemas.Unset] = schemas.unset,
        expirationDate: typing.Union[MetaOapg.properties.expirationDate, str, schemas.Unset] = schemas.unset,
        expiration: typing.Union[MetaOapg.properties.expiration, str, schemas.Unset] = schemas.unset,
        firstSix: typing.Union[MetaOapg.properties.firstSix, str, schemas.Unset] = schemas.unset,
        lastFour: typing.Union[MetaOapg.properties.lastFour, str, schemas.Unset] = schemas.unset,
        nameLine1: typing.Union[MetaOapg.properties.nameLine1, str, schemas.Unset] = schemas.unset,
        nameLine2: typing.Union[MetaOapg.properties.nameLine2, str, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        cardType: typing.Union[MetaOapg.properties.cardType, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CardCancelVirtualCardResponseCard':
        return super().__new__(
            cls,
            *args,
            cardGuid=cardGuid,
            amountLimit=amountLimit,
            usageLimit=usageLimit,
            limitWindow=limitWindow,
            expirationDate=expirationDate,
            expiration=expiration,
            firstSix=firstSix,
            lastFour=lastFour,
            nameLine1=nameLine1,
            nameLine2=nameLine2,
            status=status,
            cardType=cardType,
            _configuration=_configuration,
            **kwargs,
        )
