# coding: utf-8

"""
    ConnexPay Reporting API

    REST API for retrieving reporting data. Currently Daily Accounting data only.

    The version of the OpenAPI document: v1
    Created by: https://docs.connexpay.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from connex_pay_python_sdk import schemas  # noqa: F401


class CardCreateLodgedCardRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "MerchantGuid",
            "FirstName",
            "LastName",
            "LimitWindow",
            "AmountLimit",
        }
        
        class properties:
            MerchantGuid = schemas.StrSchema
            FirstName = schemas.StrSchema
            LastName = schemas.StrSchema
            AmountLimit = schemas.Float32Schema
            LimitWindow = schemas.StrSchema
            Phone = schemas.StrSchema
            Address1 = schemas.StrSchema
            Address2 = schemas.StrSchema
            City = schemas.StrSchema
            State = schemas.StrSchema
            ZipCode = schemas.StrSchema
            Country = schemas.StrSchema
            UsageLimit = schemas.Int64Schema
            ExpirationDate = schemas.DateSchema
            TerminateDate = schemas.DateSchema
            PurchaseType = schemas.StrSchema
            SequenceNumber = schemas.StrSchema
            OrderNumber = schemas.StrSchema
            SupplierId = schemas.StrSchema
            NonDomesticSupplier = schemas.BoolSchema
        
            @staticmethod
            def Transmission() -> typing.Type['CardCreateLodgedCardRequestTransmission']:
                return CardCreateLodgedCardRequestTransmission
            ReturnCardData = schemas.BoolSchema
            CustomerID = schemas.StrSchema
            AssociationId = schemas.StrSchema
        
            @staticmethod
            def LabelIDs() -> typing.Type['CardCreateLodgedCardRequestLabelIDs']:
                return CardCreateLodgedCardRequestLabelIDs
        
            @staticmethod
            def CustomParameters() -> typing.Type['CardCreateLodgedCardRequestCustomParameters']:
                return CardCreateLodgedCardRequestCustomParameters
            __annotations__ = {
                "MerchantGuid": MerchantGuid,
                "FirstName": FirstName,
                "LastName": LastName,
                "AmountLimit": AmountLimit,
                "LimitWindow": LimitWindow,
                "Phone": Phone,
                "Address1": Address1,
                "Address2": Address2,
                "City": City,
                "State": State,
                "ZipCode": ZipCode,
                "Country": Country,
                "UsageLimit": UsageLimit,
                "ExpirationDate": ExpirationDate,
                "TerminateDate": TerminateDate,
                "PurchaseType": PurchaseType,
                "SequenceNumber": SequenceNumber,
                "OrderNumber": OrderNumber,
                "SupplierId": SupplierId,
                "NonDomesticSupplier": NonDomesticSupplier,
                "Transmission": Transmission,
                "ReturnCardData": ReturnCardData,
                "CustomerID": CustomerID,
                "AssociationId": AssociationId,
                "LabelIDs": LabelIDs,
                "CustomParameters": CustomParameters,
            }
    
    MerchantGuid: MetaOapg.properties.MerchantGuid
    FirstName: MetaOapg.properties.FirstName
    LastName: MetaOapg.properties.LastName
    LimitWindow: MetaOapg.properties.LimitWindow
    AmountLimit: MetaOapg.properties.AmountLimit
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["MerchantGuid"]) -> MetaOapg.properties.MerchantGuid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["FirstName"]) -> MetaOapg.properties.FirstName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LastName"]) -> MetaOapg.properties.LastName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["AmountLimit"]) -> MetaOapg.properties.AmountLimit: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LimitWindow"]) -> MetaOapg.properties.LimitWindow: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Phone"]) -> MetaOapg.properties.Phone: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Address1"]) -> MetaOapg.properties.Address1: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Address2"]) -> MetaOapg.properties.Address2: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["City"]) -> MetaOapg.properties.City: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["State"]) -> MetaOapg.properties.State: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ZipCode"]) -> MetaOapg.properties.ZipCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Country"]) -> MetaOapg.properties.Country: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["UsageLimit"]) -> MetaOapg.properties.UsageLimit: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ExpirationDate"]) -> MetaOapg.properties.ExpirationDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["TerminateDate"]) -> MetaOapg.properties.TerminateDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PurchaseType"]) -> MetaOapg.properties.PurchaseType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["SequenceNumber"]) -> MetaOapg.properties.SequenceNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["OrderNumber"]) -> MetaOapg.properties.OrderNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["SupplierId"]) -> MetaOapg.properties.SupplierId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["NonDomesticSupplier"]) -> MetaOapg.properties.NonDomesticSupplier: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Transmission"]) -> 'CardCreateLodgedCardRequestTransmission': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ReturnCardData"]) -> MetaOapg.properties.ReturnCardData: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["CustomerID"]) -> MetaOapg.properties.CustomerID: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["AssociationId"]) -> MetaOapg.properties.AssociationId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LabelIDs"]) -> 'CardCreateLodgedCardRequestLabelIDs': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["CustomParameters"]) -> 'CardCreateLodgedCardRequestCustomParameters': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["MerchantGuid", "FirstName", "LastName", "AmountLimit", "LimitWindow", "Phone", "Address1", "Address2", "City", "State", "ZipCode", "Country", "UsageLimit", "ExpirationDate", "TerminateDate", "PurchaseType", "SequenceNumber", "OrderNumber", "SupplierId", "NonDomesticSupplier", "Transmission", "ReturnCardData", "CustomerID", "AssociationId", "LabelIDs", "CustomParameters", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["MerchantGuid"]) -> MetaOapg.properties.MerchantGuid: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["FirstName"]) -> MetaOapg.properties.FirstName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LastName"]) -> MetaOapg.properties.LastName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["AmountLimit"]) -> MetaOapg.properties.AmountLimit: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LimitWindow"]) -> MetaOapg.properties.LimitWindow: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Phone"]) -> typing.Union[MetaOapg.properties.Phone, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Address1"]) -> typing.Union[MetaOapg.properties.Address1, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Address2"]) -> typing.Union[MetaOapg.properties.Address2, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["City"]) -> typing.Union[MetaOapg.properties.City, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["State"]) -> typing.Union[MetaOapg.properties.State, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ZipCode"]) -> typing.Union[MetaOapg.properties.ZipCode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Country"]) -> typing.Union[MetaOapg.properties.Country, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["UsageLimit"]) -> typing.Union[MetaOapg.properties.UsageLimit, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ExpirationDate"]) -> typing.Union[MetaOapg.properties.ExpirationDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["TerminateDate"]) -> typing.Union[MetaOapg.properties.TerminateDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PurchaseType"]) -> typing.Union[MetaOapg.properties.PurchaseType, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["SequenceNumber"]) -> typing.Union[MetaOapg.properties.SequenceNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["OrderNumber"]) -> typing.Union[MetaOapg.properties.OrderNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["SupplierId"]) -> typing.Union[MetaOapg.properties.SupplierId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["NonDomesticSupplier"]) -> typing.Union[MetaOapg.properties.NonDomesticSupplier, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Transmission"]) -> typing.Union['CardCreateLodgedCardRequestTransmission', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ReturnCardData"]) -> typing.Union[MetaOapg.properties.ReturnCardData, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["CustomerID"]) -> typing.Union[MetaOapg.properties.CustomerID, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["AssociationId"]) -> typing.Union[MetaOapg.properties.AssociationId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LabelIDs"]) -> typing.Union['CardCreateLodgedCardRequestLabelIDs', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["CustomParameters"]) -> typing.Union['CardCreateLodgedCardRequestCustomParameters', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["MerchantGuid", "FirstName", "LastName", "AmountLimit", "LimitWindow", "Phone", "Address1", "Address2", "City", "State", "ZipCode", "Country", "UsageLimit", "ExpirationDate", "TerminateDate", "PurchaseType", "SequenceNumber", "OrderNumber", "SupplierId", "NonDomesticSupplier", "Transmission", "ReturnCardData", "CustomerID", "AssociationId", "LabelIDs", "CustomParameters", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        MerchantGuid: typing.Union[MetaOapg.properties.MerchantGuid, str, ],
        FirstName: typing.Union[MetaOapg.properties.FirstName, str, ],
        LastName: typing.Union[MetaOapg.properties.LastName, str, ],
        LimitWindow: typing.Union[MetaOapg.properties.LimitWindow, str, ],
        AmountLimit: typing.Union[MetaOapg.properties.AmountLimit, decimal.Decimal, int, float, ],
        Phone: typing.Union[MetaOapg.properties.Phone, str, schemas.Unset] = schemas.unset,
        Address1: typing.Union[MetaOapg.properties.Address1, str, schemas.Unset] = schemas.unset,
        Address2: typing.Union[MetaOapg.properties.Address2, str, schemas.Unset] = schemas.unset,
        City: typing.Union[MetaOapg.properties.City, str, schemas.Unset] = schemas.unset,
        State: typing.Union[MetaOapg.properties.State, str, schemas.Unset] = schemas.unset,
        ZipCode: typing.Union[MetaOapg.properties.ZipCode, str, schemas.Unset] = schemas.unset,
        Country: typing.Union[MetaOapg.properties.Country, str, schemas.Unset] = schemas.unset,
        UsageLimit: typing.Union[MetaOapg.properties.UsageLimit, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        ExpirationDate: typing.Union[MetaOapg.properties.ExpirationDate, str, date, schemas.Unset] = schemas.unset,
        TerminateDate: typing.Union[MetaOapg.properties.TerminateDate, str, date, schemas.Unset] = schemas.unset,
        PurchaseType: typing.Union[MetaOapg.properties.PurchaseType, str, schemas.Unset] = schemas.unset,
        SequenceNumber: typing.Union[MetaOapg.properties.SequenceNumber, str, schemas.Unset] = schemas.unset,
        OrderNumber: typing.Union[MetaOapg.properties.OrderNumber, str, schemas.Unset] = schemas.unset,
        SupplierId: typing.Union[MetaOapg.properties.SupplierId, str, schemas.Unset] = schemas.unset,
        NonDomesticSupplier: typing.Union[MetaOapg.properties.NonDomesticSupplier, bool, schemas.Unset] = schemas.unset,
        Transmission: typing.Union['CardCreateLodgedCardRequestTransmission', schemas.Unset] = schemas.unset,
        ReturnCardData: typing.Union[MetaOapg.properties.ReturnCardData, bool, schemas.Unset] = schemas.unset,
        CustomerID: typing.Union[MetaOapg.properties.CustomerID, str, schemas.Unset] = schemas.unset,
        AssociationId: typing.Union[MetaOapg.properties.AssociationId, str, schemas.Unset] = schemas.unset,
        LabelIDs: typing.Union['CardCreateLodgedCardRequestLabelIDs', schemas.Unset] = schemas.unset,
        CustomParameters: typing.Union['CardCreateLodgedCardRequestCustomParameters', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CardCreateLodgedCardRequest':
        return super().__new__(
            cls,
            *args,
            MerchantGuid=MerchantGuid,
            FirstName=FirstName,
            LastName=LastName,
            LimitWindow=LimitWindow,
            AmountLimit=AmountLimit,
            Phone=Phone,
            Address1=Address1,
            Address2=Address2,
            City=City,
            State=State,
            ZipCode=ZipCode,
            Country=Country,
            UsageLimit=UsageLimit,
            ExpirationDate=ExpirationDate,
            TerminateDate=TerminateDate,
            PurchaseType=PurchaseType,
            SequenceNumber=SequenceNumber,
            OrderNumber=OrderNumber,
            SupplierId=SupplierId,
            NonDomesticSupplier=NonDomesticSupplier,
            Transmission=Transmission,
            ReturnCardData=ReturnCardData,
            CustomerID=CustomerID,
            AssociationId=AssociationId,
            LabelIDs=LabelIDs,
            CustomParameters=CustomParameters,
            _configuration=_configuration,
            **kwargs,
        )

from connex_pay_python_sdk.model.card_create_lodged_card_request_custom_parameters import CardCreateLodgedCardRequestCustomParameters
from connex_pay_python_sdk.model.card_create_lodged_card_request_label_ids import CardCreateLodgedCardRequestLabelIDs
from connex_pay_python_sdk.model.card_create_lodged_card_request_transmission import CardCreateLodgedCardRequestTransmission
