# coding: utf-8

"""
    ConnexPay Reporting API

    REST API for retrieving reporting data. Currently Daily Accounting data only.

    The version of the OpenAPI document: v1
    Created by: https://docs.connexpay.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from connex_pay_python_sdk import schemas  # noqa: F401


class CardUpdateLodgedCardResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def card() -> typing.Type['CardUpdateLodgedCardResponseCard']:
                return CardUpdateLodgedCardResponseCard
            mccGroupName = schemas.StrSchema
            __annotations__ = {
                "card": card,
                "mccGroupName": mccGroupName,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["card"]) -> 'CardUpdateLodgedCardResponseCard': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mccGroupName"]) -> MetaOapg.properties.mccGroupName: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["card", "mccGroupName", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["card"]) -> typing.Union['CardUpdateLodgedCardResponseCard', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mccGroupName"]) -> typing.Union[MetaOapg.properties.mccGroupName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["card", "mccGroupName", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        card: typing.Union['CardUpdateLodgedCardResponseCard', schemas.Unset] = schemas.unset,
        mccGroupName: typing.Union[MetaOapg.properties.mccGroupName, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CardUpdateLodgedCardResponse':
        return super().__new__(
            cls,
            *args,
            card=card,
            mccGroupName=mccGroupName,
            _configuration=_configuration,
            **kwargs,
        )

from connex_pay_python_sdk.model.card_update_lodged_card_response_card import CardUpdateLodgedCardResponseCard
