# coding: utf-8

"""
    ConnexPay Reporting API

    REST API for retrieving reporting data. Currently Daily Accounting data only.

    The version of the OpenAPI document: v1
    Created by: https://docs.connexpay.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from connex_pay_python_sdk import schemas  # noqa: F401


class CardUpdateDelayedActivationRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "MerchantGuid",
        }
        
        class properties:
            MerchantGuid = schemas.StrSchema
            ActivationDate = schemas.DateSchema
            AmountLimit = schemas.Float32Schema
            TerminateDate = schemas.DateSchema
            __annotations__ = {
                "MerchantGuid": MerchantGuid,
                "ActivationDate": ActivationDate,
                "AmountLimit": AmountLimit,
                "TerminateDate": TerminateDate,
            }
    
    MerchantGuid: MetaOapg.properties.MerchantGuid
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["MerchantGuid"]) -> MetaOapg.properties.MerchantGuid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ActivationDate"]) -> MetaOapg.properties.ActivationDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["AmountLimit"]) -> MetaOapg.properties.AmountLimit: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["TerminateDate"]) -> MetaOapg.properties.TerminateDate: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["MerchantGuid", "ActivationDate", "AmountLimit", "TerminateDate", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["MerchantGuid"]) -> MetaOapg.properties.MerchantGuid: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ActivationDate"]) -> typing.Union[MetaOapg.properties.ActivationDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["AmountLimit"]) -> typing.Union[MetaOapg.properties.AmountLimit, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["TerminateDate"]) -> typing.Union[MetaOapg.properties.TerminateDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["MerchantGuid", "ActivationDate", "AmountLimit", "TerminateDate", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        MerchantGuid: typing.Union[MetaOapg.properties.MerchantGuid, str, ],
        ActivationDate: typing.Union[MetaOapg.properties.ActivationDate, str, date, schemas.Unset] = schemas.unset,
        AmountLimit: typing.Union[MetaOapg.properties.AmountLimit, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        TerminateDate: typing.Union[MetaOapg.properties.TerminateDate, str, date, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CardUpdateDelayedActivationRequest':
        return super().__new__(
            cls,
            *args,
            MerchantGuid=MerchantGuid,
            ActivationDate=ActivationDate,
            AmountLimit=AmountLimit,
            TerminateDate=TerminateDate,
            _configuration=_configuration,
            **kwargs,
        )
