# coding: utf-8

"""
    ConnexPay Reporting API

    REST API for retrieving reporting data. Currently Daily Accounting data only.

    The version of the OpenAPI document: v1
    Created by: https://docs.connexpay.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from connex_pay_python_sdk import schemas  # noqa: F401


class FundingTransferMerchantCashBalanceResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            TransferredFrom = schemas.StrSchema
            TransferredTo = schemas.StrSchema
            Amount = schemas.IntSchema
            __annotations__ = {
                "TransferredFrom": TransferredFrom,
                "TransferredTo": TransferredTo,
                "Amount": Amount,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["TransferredFrom"]) -> MetaOapg.properties.TransferredFrom: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["TransferredTo"]) -> MetaOapg.properties.TransferredTo: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Amount"]) -> MetaOapg.properties.Amount: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["TransferredFrom", "TransferredTo", "Amount", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["TransferredFrom"]) -> typing.Union[MetaOapg.properties.TransferredFrom, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["TransferredTo"]) -> typing.Union[MetaOapg.properties.TransferredTo, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Amount"]) -> typing.Union[MetaOapg.properties.Amount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["TransferredFrom", "TransferredTo", "Amount", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        TransferredFrom: typing.Union[MetaOapg.properties.TransferredFrom, str, schemas.Unset] = schemas.unset,
        TransferredTo: typing.Union[MetaOapg.properties.TransferredTo, str, schemas.Unset] = schemas.unset,
        Amount: typing.Union[MetaOapg.properties.Amount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FundingTransferMerchantCashBalanceResponse':
        return super().__new__(
            cls,
            *args,
            TransferredFrom=TransferredFrom,
            TransferredTo=TransferredTo,
            Amount=Amount,
            _configuration=_configuration,
            **kwargs,
        )
