# coding: utf-8

"""
    ConnexPay Reporting API

    REST API for retrieving reporting data. Currently Daily Accounting data only.

    The version of the OpenAPI document: v1
    Created by: https://docs.connexpay.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from connex_pay_python_sdk import schemas  # noqa: F401


class FundingMerchantCashBalance500Response(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            message = schemas.StrSchema
            exceptionMessage = schemas.StrSchema
            exceptionType = schemas.StrSchema
            stackTrace = schemas.StrSchema
            __annotations__ = {
                "message": message,
                "exceptionMessage": exceptionMessage,
                "exceptionType": exceptionType,
                "stackTrace": stackTrace,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["message"]) -> MetaOapg.properties.message: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["exceptionMessage"]) -> MetaOapg.properties.exceptionMessage: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["exceptionType"]) -> MetaOapg.properties.exceptionType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["stackTrace"]) -> MetaOapg.properties.stackTrace: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["message", "exceptionMessage", "exceptionType", "stackTrace", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["message"]) -> typing.Union[MetaOapg.properties.message, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["exceptionMessage"]) -> typing.Union[MetaOapg.properties.exceptionMessage, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["exceptionType"]) -> typing.Union[MetaOapg.properties.exceptionType, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["stackTrace"]) -> typing.Union[MetaOapg.properties.stackTrace, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["message", "exceptionMessage", "exceptionType", "stackTrace", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        message: typing.Union[MetaOapg.properties.message, str, schemas.Unset] = schemas.unset,
        exceptionMessage: typing.Union[MetaOapg.properties.exceptionMessage, str, schemas.Unset] = schemas.unset,
        exceptionType: typing.Union[MetaOapg.properties.exceptionType, str, schemas.Unset] = schemas.unset,
        stackTrace: typing.Union[MetaOapg.properties.stackTrace, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FundingMerchantCashBalance500Response':
        return super().__new__(
            cls,
            *args,
            message=message,
            exceptionMessage=exceptionMessage,
            exceptionType=exceptionType,
            stackTrace=stackTrace,
            _configuration=_configuration,
            **kwargs,
        )
