# coding: utf-8

"""
    ConnexPay Reporting API

    REST API for retrieving reporting data. Currently Daily Accounting data only.

    The version of the OpenAPI document: v1
    Created by: https://docs.connexpay.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from connex_pay_python_sdk import schemas  # noqa: F401


class ReturnItemRequestRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "DeviceGuid",
            "Amount",
        }
        
        class properties:
            DeviceGuid = schemas.StrSchema
            Amount = schemas.Float32Schema
            SaleGuid = schemas.StrSchema
            SaleReferenceNumber = schemas.Int32Schema
            SequenceNumber = schemas.StrSchema
        
            @staticmethod
            def ReturnRetryCard() -> typing.Type['ReturnItemRequestRequestReturnRetryCard']:
                return ReturnItemRequestRequestReturnRetryCard
            __annotations__ = {
                "DeviceGuid": DeviceGuid,
                "Amount": Amount,
                "SaleGuid": SaleGuid,
                "SaleReferenceNumber": SaleReferenceNumber,
                "SequenceNumber": SequenceNumber,
                "ReturnRetryCard": ReturnRetryCard,
            }
    
    DeviceGuid: MetaOapg.properties.DeviceGuid
    Amount: MetaOapg.properties.Amount
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["DeviceGuid"]) -> MetaOapg.properties.DeviceGuid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Amount"]) -> MetaOapg.properties.Amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["SaleGuid"]) -> MetaOapg.properties.SaleGuid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["SaleReferenceNumber"]) -> MetaOapg.properties.SaleReferenceNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["SequenceNumber"]) -> MetaOapg.properties.SequenceNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ReturnRetryCard"]) -> 'ReturnItemRequestRequestReturnRetryCard': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["DeviceGuid", "Amount", "SaleGuid", "SaleReferenceNumber", "SequenceNumber", "ReturnRetryCard", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["DeviceGuid"]) -> MetaOapg.properties.DeviceGuid: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Amount"]) -> MetaOapg.properties.Amount: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["SaleGuid"]) -> typing.Union[MetaOapg.properties.SaleGuid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["SaleReferenceNumber"]) -> typing.Union[MetaOapg.properties.SaleReferenceNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["SequenceNumber"]) -> typing.Union[MetaOapg.properties.SequenceNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ReturnRetryCard"]) -> typing.Union['ReturnItemRequestRequestReturnRetryCard', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["DeviceGuid", "Amount", "SaleGuid", "SaleReferenceNumber", "SequenceNumber", "ReturnRetryCard", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        DeviceGuid: typing.Union[MetaOapg.properties.DeviceGuid, str, ],
        Amount: typing.Union[MetaOapg.properties.Amount, decimal.Decimal, int, float, ],
        SaleGuid: typing.Union[MetaOapg.properties.SaleGuid, str, schemas.Unset] = schemas.unset,
        SaleReferenceNumber: typing.Union[MetaOapg.properties.SaleReferenceNumber, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        SequenceNumber: typing.Union[MetaOapg.properties.SequenceNumber, str, schemas.Unset] = schemas.unset,
        ReturnRetryCard: typing.Union['ReturnItemRequestRequestReturnRetryCard', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ReturnItemRequestRequest':
        return super().__new__(
            cls,
            *args,
            DeviceGuid=DeviceGuid,
            Amount=Amount,
            SaleGuid=SaleGuid,
            SaleReferenceNumber=SaleReferenceNumber,
            SequenceNumber=SequenceNumber,
            ReturnRetryCard=ReturnRetryCard,
            _configuration=_configuration,
            **kwargs,
        )

from connex_pay_python_sdk.model.return_item_request_request_return_retry_card import ReturnItemRequestRequestReturnRetryCard
