# coding: utf-8

"""
    ConnexPay Reporting API

    REST API for retrieving reporting data. Currently Daily Accounting data only.

    The version of the OpenAPI document: v1
    Created by: https://docs.connexpay.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from connex_pay_python_sdk import schemas  # noqa: F401


class SaleCreateTransaction201Response(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            guid = schemas.StrSchema
            status = schemas.StrSchema
            type = schemas.StrSchema
            batchStatus = schemas.StrSchema
            timeStamp = schemas.StrSchema
            deviceGuid = schemas.StrSchema
            amount = schemas.NumberSchema
            activated = schemas.BoolSchema
            tenderType = schemas.StrSchema
            effectiveAmount = schemas.NumberSchema
            purchaseActivationDate = schemas.StrSchema
            orderNumber = schemas.StrSchema
            cardDataSource = schemas.StrSchema
            customerID = schemas.StrSchema
            batchGuid = schemas.StrSchema
        
            @staticmethod
            def connexPayTransaction() -> typing.Type['SaleCreateTransaction201ResponseConnexPayTransaction']:
                return SaleCreateTransaction201ResponseConnexPayTransaction
            riskProcessingOnly = schemas.BoolSchema
            processorStatusCode = schemas.StrSchema
            processorResponseMessage = schemas.StrSchema
            wasProcessed = schemas.BoolSchema
            refNumber = schemas.StrSchema
            customerReceipt = schemas.StrSchema
            statementDescription = schemas.StrSchema
            generatedBy = schemas.StrSchema
        
            @staticmethod
            def bankAccount() -> typing.Type['SaleCreateTransaction201ResponseBankAccount']:
                return SaleCreateTransaction201ResponseBankAccount
            sequenceNumber = schemas.StrSchema
            addressVerificationResult = schemas.StrSchema
            cvvVerificationResult = schemas.StrSchema
            walletProvider = schemas.IntSchema
            includeRiskAnalysis = schemas.BoolSchema
            isFromIssueLite = schemas.BoolSchema
            remainingAmount = schemas.NumberSchema
            __annotations__ = {
                "guid": guid,
                "status": status,
                "type": type,
                "batchStatus": batchStatus,
                "timeStamp": timeStamp,
                "deviceGuid": deviceGuid,
                "amount": amount,
                "activated": activated,
                "tenderType": tenderType,
                "effectiveAmount": effectiveAmount,
                "purchaseActivationDate": purchaseActivationDate,
                "orderNumber": orderNumber,
                "cardDataSource": cardDataSource,
                "customerID": customerID,
                "batchGuid": batchGuid,
                "connexPayTransaction": connexPayTransaction,
                "riskProcessingOnly": riskProcessingOnly,
                "processorStatusCode": processorStatusCode,
                "processorResponseMessage": processorResponseMessage,
                "wasProcessed": wasProcessed,
                "refNumber": refNumber,
                "customerReceipt": customerReceipt,
                "statementDescription": statementDescription,
                "generatedBy": generatedBy,
                "bankAccount": bankAccount,
                "sequenceNumber": sequenceNumber,
                "addressVerificationResult": addressVerificationResult,
                "cvvVerificationResult": cvvVerificationResult,
                "walletProvider": walletProvider,
                "includeRiskAnalysis": includeRiskAnalysis,
                "isFromIssueLite": isFromIssueLite,
                "remainingAmount": remainingAmount,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["guid"]) -> MetaOapg.properties.guid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["batchStatus"]) -> MetaOapg.properties.batchStatus: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timeStamp"]) -> MetaOapg.properties.timeStamp: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["deviceGuid"]) -> MetaOapg.properties.deviceGuid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["activated"]) -> MetaOapg.properties.activated: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tenderType"]) -> MetaOapg.properties.tenderType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["effectiveAmount"]) -> MetaOapg.properties.effectiveAmount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["purchaseActivationDate"]) -> MetaOapg.properties.purchaseActivationDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["orderNumber"]) -> MetaOapg.properties.orderNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cardDataSource"]) -> MetaOapg.properties.cardDataSource: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["customerID"]) -> MetaOapg.properties.customerID: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["batchGuid"]) -> MetaOapg.properties.batchGuid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["connexPayTransaction"]) -> 'SaleCreateTransaction201ResponseConnexPayTransaction': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["riskProcessingOnly"]) -> MetaOapg.properties.riskProcessingOnly: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["processorStatusCode"]) -> MetaOapg.properties.processorStatusCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["processorResponseMessage"]) -> MetaOapg.properties.processorResponseMessage: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["wasProcessed"]) -> MetaOapg.properties.wasProcessed: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["refNumber"]) -> MetaOapg.properties.refNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["customerReceipt"]) -> MetaOapg.properties.customerReceipt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["statementDescription"]) -> MetaOapg.properties.statementDescription: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["generatedBy"]) -> MetaOapg.properties.generatedBy: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bankAccount"]) -> 'SaleCreateTransaction201ResponseBankAccount': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sequenceNumber"]) -> MetaOapg.properties.sequenceNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["addressVerificationResult"]) -> MetaOapg.properties.addressVerificationResult: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cvvVerificationResult"]) -> MetaOapg.properties.cvvVerificationResult: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["walletProvider"]) -> MetaOapg.properties.walletProvider: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["includeRiskAnalysis"]) -> MetaOapg.properties.includeRiskAnalysis: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["isFromIssueLite"]) -> MetaOapg.properties.isFromIssueLite: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["remainingAmount"]) -> MetaOapg.properties.remainingAmount: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["guid", "status", "type", "batchStatus", "timeStamp", "deviceGuid", "amount", "activated", "tenderType", "effectiveAmount", "purchaseActivationDate", "orderNumber", "cardDataSource", "customerID", "batchGuid", "connexPayTransaction", "riskProcessingOnly", "processorStatusCode", "processorResponseMessage", "wasProcessed", "refNumber", "customerReceipt", "statementDescription", "generatedBy", "bankAccount", "sequenceNumber", "addressVerificationResult", "cvvVerificationResult", "walletProvider", "includeRiskAnalysis", "isFromIssueLite", "remainingAmount", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["guid"]) -> typing.Union[MetaOapg.properties.guid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> typing.Union[MetaOapg.properties.type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["batchStatus"]) -> typing.Union[MetaOapg.properties.batchStatus, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timeStamp"]) -> typing.Union[MetaOapg.properties.timeStamp, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["deviceGuid"]) -> typing.Union[MetaOapg.properties.deviceGuid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amount"]) -> typing.Union[MetaOapg.properties.amount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["activated"]) -> typing.Union[MetaOapg.properties.activated, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tenderType"]) -> typing.Union[MetaOapg.properties.tenderType, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["effectiveAmount"]) -> typing.Union[MetaOapg.properties.effectiveAmount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["purchaseActivationDate"]) -> typing.Union[MetaOapg.properties.purchaseActivationDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["orderNumber"]) -> typing.Union[MetaOapg.properties.orderNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cardDataSource"]) -> typing.Union[MetaOapg.properties.cardDataSource, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["customerID"]) -> typing.Union[MetaOapg.properties.customerID, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["batchGuid"]) -> typing.Union[MetaOapg.properties.batchGuid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["connexPayTransaction"]) -> typing.Union['SaleCreateTransaction201ResponseConnexPayTransaction', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["riskProcessingOnly"]) -> typing.Union[MetaOapg.properties.riskProcessingOnly, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["processorStatusCode"]) -> typing.Union[MetaOapg.properties.processorStatusCode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["processorResponseMessage"]) -> typing.Union[MetaOapg.properties.processorResponseMessage, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["wasProcessed"]) -> typing.Union[MetaOapg.properties.wasProcessed, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["refNumber"]) -> typing.Union[MetaOapg.properties.refNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["customerReceipt"]) -> typing.Union[MetaOapg.properties.customerReceipt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["statementDescription"]) -> typing.Union[MetaOapg.properties.statementDescription, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["generatedBy"]) -> typing.Union[MetaOapg.properties.generatedBy, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bankAccount"]) -> typing.Union['SaleCreateTransaction201ResponseBankAccount', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sequenceNumber"]) -> typing.Union[MetaOapg.properties.sequenceNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["addressVerificationResult"]) -> typing.Union[MetaOapg.properties.addressVerificationResult, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cvvVerificationResult"]) -> typing.Union[MetaOapg.properties.cvvVerificationResult, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["walletProvider"]) -> typing.Union[MetaOapg.properties.walletProvider, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["includeRiskAnalysis"]) -> typing.Union[MetaOapg.properties.includeRiskAnalysis, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["isFromIssueLite"]) -> typing.Union[MetaOapg.properties.isFromIssueLite, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["remainingAmount"]) -> typing.Union[MetaOapg.properties.remainingAmount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["guid", "status", "type", "batchStatus", "timeStamp", "deviceGuid", "amount", "activated", "tenderType", "effectiveAmount", "purchaseActivationDate", "orderNumber", "cardDataSource", "customerID", "batchGuid", "connexPayTransaction", "riskProcessingOnly", "processorStatusCode", "processorResponseMessage", "wasProcessed", "refNumber", "customerReceipt", "statementDescription", "generatedBy", "bankAccount", "sequenceNumber", "addressVerificationResult", "cvvVerificationResult", "walletProvider", "includeRiskAnalysis", "isFromIssueLite", "remainingAmount", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        guid: typing.Union[MetaOapg.properties.guid, str, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        type: typing.Union[MetaOapg.properties.type, str, schemas.Unset] = schemas.unset,
        batchStatus: typing.Union[MetaOapg.properties.batchStatus, str, schemas.Unset] = schemas.unset,
        timeStamp: typing.Union[MetaOapg.properties.timeStamp, str, schemas.Unset] = schemas.unset,
        deviceGuid: typing.Union[MetaOapg.properties.deviceGuid, str, schemas.Unset] = schemas.unset,
        amount: typing.Union[MetaOapg.properties.amount, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        activated: typing.Union[MetaOapg.properties.activated, bool, schemas.Unset] = schemas.unset,
        tenderType: typing.Union[MetaOapg.properties.tenderType, str, schemas.Unset] = schemas.unset,
        effectiveAmount: typing.Union[MetaOapg.properties.effectiveAmount, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        purchaseActivationDate: typing.Union[MetaOapg.properties.purchaseActivationDate, str, schemas.Unset] = schemas.unset,
        orderNumber: typing.Union[MetaOapg.properties.orderNumber, str, schemas.Unset] = schemas.unset,
        cardDataSource: typing.Union[MetaOapg.properties.cardDataSource, str, schemas.Unset] = schemas.unset,
        customerID: typing.Union[MetaOapg.properties.customerID, str, schemas.Unset] = schemas.unset,
        batchGuid: typing.Union[MetaOapg.properties.batchGuid, str, schemas.Unset] = schemas.unset,
        connexPayTransaction: typing.Union['SaleCreateTransaction201ResponseConnexPayTransaction', schemas.Unset] = schemas.unset,
        riskProcessingOnly: typing.Union[MetaOapg.properties.riskProcessingOnly, bool, schemas.Unset] = schemas.unset,
        processorStatusCode: typing.Union[MetaOapg.properties.processorStatusCode, str, schemas.Unset] = schemas.unset,
        processorResponseMessage: typing.Union[MetaOapg.properties.processorResponseMessage, str, schemas.Unset] = schemas.unset,
        wasProcessed: typing.Union[MetaOapg.properties.wasProcessed, bool, schemas.Unset] = schemas.unset,
        refNumber: typing.Union[MetaOapg.properties.refNumber, str, schemas.Unset] = schemas.unset,
        customerReceipt: typing.Union[MetaOapg.properties.customerReceipt, str, schemas.Unset] = schemas.unset,
        statementDescription: typing.Union[MetaOapg.properties.statementDescription, str, schemas.Unset] = schemas.unset,
        generatedBy: typing.Union[MetaOapg.properties.generatedBy, str, schemas.Unset] = schemas.unset,
        bankAccount: typing.Union['SaleCreateTransaction201ResponseBankAccount', schemas.Unset] = schemas.unset,
        sequenceNumber: typing.Union[MetaOapg.properties.sequenceNumber, str, schemas.Unset] = schemas.unset,
        addressVerificationResult: typing.Union[MetaOapg.properties.addressVerificationResult, str, schemas.Unset] = schemas.unset,
        cvvVerificationResult: typing.Union[MetaOapg.properties.cvvVerificationResult, str, schemas.Unset] = schemas.unset,
        walletProvider: typing.Union[MetaOapg.properties.walletProvider, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        includeRiskAnalysis: typing.Union[MetaOapg.properties.includeRiskAnalysis, bool, schemas.Unset] = schemas.unset,
        isFromIssueLite: typing.Union[MetaOapg.properties.isFromIssueLite, bool, schemas.Unset] = schemas.unset,
        remainingAmount: typing.Union[MetaOapg.properties.remainingAmount, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SaleCreateTransaction201Response':
        return super().__new__(
            cls,
            *args,
            guid=guid,
            status=status,
            type=type,
            batchStatus=batchStatus,
            timeStamp=timeStamp,
            deviceGuid=deviceGuid,
            amount=amount,
            activated=activated,
            tenderType=tenderType,
            effectiveAmount=effectiveAmount,
            purchaseActivationDate=purchaseActivationDate,
            orderNumber=orderNumber,
            cardDataSource=cardDataSource,
            customerID=customerID,
            batchGuid=batchGuid,
            connexPayTransaction=connexPayTransaction,
            riskProcessingOnly=riskProcessingOnly,
            processorStatusCode=processorStatusCode,
            processorResponseMessage=processorResponseMessage,
            wasProcessed=wasProcessed,
            refNumber=refNumber,
            customerReceipt=customerReceipt,
            statementDescription=statementDescription,
            generatedBy=generatedBy,
            bankAccount=bankAccount,
            sequenceNumber=sequenceNumber,
            addressVerificationResult=addressVerificationResult,
            cvvVerificationResult=cvvVerificationResult,
            walletProvider=walletProvider,
            includeRiskAnalysis=includeRiskAnalysis,
            isFromIssueLite=isFromIssueLite,
            remainingAmount=remainingAmount,
            _configuration=_configuration,
            **kwargs,
        )

from connex_pay_python_sdk.model.sale_create_transaction201_response_bank_account import SaleCreateTransaction201ResponseBankAccount
from connex_pay_python_sdk.model.sale_create_transaction201_response_connex_pay_transaction import SaleCreateTransaction201ResponseConnexPayTransaction
