# coding: utf-8

"""
    ConnexPay Reporting API

    REST API for retrieving reporting data. Currently Daily Accounting data only.

    The version of the OpenAPI document: v1
    Created by: https://docs.connexpay.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from connex_pay_python_sdk import schemas  # noqa: F401


class SettingTokenizeBankAccountInfoRequestAccountHolderBankAccount(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Payee's Bank Account info
    """


    class MetaOapg:
        required = {
            "RoutingNumber",
            "AccountHolderName",
            "AccountType",
            "AccountNumber",
        }
        
        class properties:
            RoutingNumber = schemas.StrSchema
            AccountNumber = schemas.StrSchema
            AccountType = schemas.StrSchema
            AccountHolderName = schemas.StrSchema
            __annotations__ = {
                "RoutingNumber": RoutingNumber,
                "AccountNumber": AccountNumber,
                "AccountType": AccountType,
                "AccountHolderName": AccountHolderName,
            }
    
    RoutingNumber: MetaOapg.properties.RoutingNumber
    AccountHolderName: MetaOapg.properties.AccountHolderName
    AccountType: MetaOapg.properties.AccountType
    AccountNumber: MetaOapg.properties.AccountNumber
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["RoutingNumber"]) -> MetaOapg.properties.RoutingNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["AccountNumber"]) -> MetaOapg.properties.AccountNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["AccountType"]) -> MetaOapg.properties.AccountType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["AccountHolderName"]) -> MetaOapg.properties.AccountHolderName: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["RoutingNumber", "AccountNumber", "AccountType", "AccountHolderName", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["RoutingNumber"]) -> MetaOapg.properties.RoutingNumber: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["AccountNumber"]) -> MetaOapg.properties.AccountNumber: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["AccountType"]) -> MetaOapg.properties.AccountType: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["AccountHolderName"]) -> MetaOapg.properties.AccountHolderName: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["RoutingNumber", "AccountNumber", "AccountType", "AccountHolderName", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        RoutingNumber: typing.Union[MetaOapg.properties.RoutingNumber, str, ],
        AccountHolderName: typing.Union[MetaOapg.properties.AccountHolderName, str, ],
        AccountType: typing.Union[MetaOapg.properties.AccountType, str, ],
        AccountNumber: typing.Union[MetaOapg.properties.AccountNumber, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SettingTokenizeBankAccountInfoRequestAccountHolderBankAccount':
        return super().__new__(
            cls,
            *args,
            RoutingNumber=RoutingNumber,
            AccountHolderName=AccountHolderName,
            AccountType=AccountType,
            AccountNumber=AccountNumber,
            _configuration=_configuration,
            **kwargs,
        )
