# coding: utf-8

"""
    ConnexPay Reporting API

    REST API for retrieving reporting data. Currently Daily Accounting data only.

    The version of the OpenAPI document: v1
    Created by: https://docs.connexpay.com
"""

from connex_pay_python_sdk.paths.api_v1_addendum_ach.post import CreateAchPurchaseRaw
from connex_pay_python_sdk.paths.api_v1_addendum_virtual_card.post import CreateVirtualCardRaw
from connex_pay_python_sdk.paths.v1_addendum_remove_guid.post import DeleteItemRaw


class AddendumApiRaw(
    CreateAchPurchaseRaw,
    CreateVirtualCardRaw,
    DeleteItemRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
