# coding: utf-8

"""
    ConnexPay Reporting API

    REST API for retrieving reporting data. Currently Daily Accounting data only.

    The version of the OpenAPI document: v1
    Created by: https://docs.connexpay.com
"""

from connex_pay_python_sdk.paths.api_v1_authonlys.post import AcquireClientAuthorization
from connex_pay_python_sdk.paths.api_v1_3ds.post import Obtain3dSecureAuthentication
from connex_pay_python_sdk.apis.tags.authentication_api_raw import AuthenticationApiRaw


class AuthenticationApi(
    AcquireClientAuthorization,
    Obtain3dSecureAuthentication,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AuthenticationApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AuthenticationApiRaw(api_client)
