# coding: utf-8

"""
    ConnexPay Reporting API

    REST API for retrieving reporting data. Currently Daily Accounting data only.

    The version of the OpenAPI document: v1
    Created by: https://docs.connexpay.com
"""

from connex_pay_python_sdk.paths.api_v1_issue_card.post import CreateVirtualCard
from connex_pay_python_sdk.apis.tags.card_issuance_api_raw import CardIssuanceApiRaw


class CardIssuanceApi(
    CreateVirtualCard,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CardIssuanceApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CardIssuanceApiRaw(api_client)
