# coding: utf-8

"""
    ConnexPay Reporting API

    REST API for retrieving reporting data. Currently Daily Accounting data only.

    The version of the OpenAPI document: v1
    Created by: https://docs.connexpay.com
"""

from connex_pay_python_sdk.paths.api_v1_search_available_funds_merchant_guid.get import GetAvailableDetails
from connex_pay_python_sdk.apis.tags.funds_api_raw import FundsApiRaw


class FundsApi(
    GetAvailableDetails,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: FundsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = FundsApiRaw(api_client)
