# coding: utf-8

"""
    ConnexPay Reporting API

    REST API for retrieving reporting data. Currently Daily Accounting data only.

    The version of the OpenAPI document: v1
    Created by: https://docs.connexpay.com
"""

from connex_pay_python_sdk.paths.api_v1_merchants_merchant_guid_payees.post import CreatePayeeRaw
from connex_pay_python_sdk.paths.api_v1_merchants_merchant_guid_payees_payee_guid.delete import DeletePayeeRaw
from connex_pay_python_sdk.paths.api_v1_merchants_merchant_guid_payees_payee_guid.get import GetPayeeRaw
from connex_pay_python_sdk.paths.api_v1_merchants_merchant_guid_payees_search_page_pagesize.post import GetPayeesRaw
from connex_pay_python_sdk.paths.api_v1_merchants_merchant_guid_payees_payee_guid.put import UpdatePayeeRaw


class MerchantPayeesApiRaw(
    CreatePayeeRaw,
    DeletePayeeRaw,
    GetPayeeRaw,
    GetPayeesRaw,
    UpdatePayeeRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
