# coding: utf-8

"""
    ConnexPay Reporting API

    REST API for retrieving reporting data. Currently Daily Accounting data only.

    The version of the OpenAPI document: v1
    Created by: https://docs.connexpay.com
"""

from connex_pay_python_sdk.paths.api_v1_merchants_merchant_guid_payees.post import CreatePayee
from connex_pay_python_sdk.paths.api_v1_merchants_merchant_guid_payees_payee_guid.delete import DeletePayee
from connex_pay_python_sdk.paths.api_v1_merchants_merchant_guid_payees_payee_guid.get import GetPayee
from connex_pay_python_sdk.paths.api_v1_merchants_merchant_guid_payees_search_page_pagesize.post import GetPayees
from connex_pay_python_sdk.paths.api_v1_merchants_merchant_guid_payees_payee_guid.put import UpdatePayee
from connex_pay_python_sdk.apis.tags.merchant_payees_api_raw import MerchantPayeesApiRaw


class MerchantPayeesApi(
    CreatePayee,
    DeletePayee,
    GetPayee,
    GetPayees,
    UpdatePayee,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: MerchantPayeesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = MerchantPayeesApiRaw(api_client)
