# coding: utf-8

"""
    ConnexPay Reporting API

    REST API for retrieving reporting data. Currently Daily Accounting data only.

    The version of the OpenAPI document: v1
    Created by: https://docs.connexpay.com
"""

from connex_pay_python_sdk.paths.api_v1_merchantsupplier_settings.post import TokenizeBankAccountInfo
from connex_pay_python_sdk.apis.tags.setting_api_raw import SettingApiRaw


class SettingApi(
    TokenizeBankAccountInfo,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SettingApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SettingApiRaw(api_client)
