# coding: utf-8

"""
    ConnexPay Reporting API

    REST API for retrieving reporting data. Currently Daily Accounting data only.

    The version of the OpenAPI document: v1
    Created by: https://docs.connexpay.com
"""

from connex_pay_python_sdk.paths.api_v1_search_settlements.post import SearchVirtualCardSettlements
from connex_pay_python_sdk.apis.tags.settlement_api_raw import SettlementApiRaw


class SettlementApi(
    SearchVirtualCardSettlements,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SettlementApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SettlementApiRaw(api_client)
