# coding: utf-8

"""
    ConnexPay Reporting API

    REST API for retrieving reporting data. Currently Daily Accounting data only.

    The version of the OpenAPI document: v1
    Created by: https://docs.connexpay.com
"""

from connex_pay_python_sdk.paths.api_v1_3ds_guid.get import Call3dsAuthenticationStatus
from connex_pay_python_sdk.apis.tags.status_group_api_raw import StatusGroupApiRaw


class StatusGroupApi(
    Call3dsAuthenticationStatus,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: StatusGroupApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = StatusGroupApiRaw(api_client)
