# coding: utf-8

"""
    ConnexPay Reporting API

    REST API for retrieving reporting data. Currently Daily Accounting data only.

    The version of the OpenAPI document: v1
    Created by: https://docs.connexpay.com
"""

from connex_pay_python_sdk.paths.api_v1_void.post import CreateVoid
from connex_pay_python_sdk.paths.api_v1_search_voids_exportable_page_number_page_size.post import SearchVoids
from connex_pay_python_sdk.apis.tags.void_api_raw import VoidApiRaw


class VoidApi(
    CreateVoid,
    SearchVoids,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: VoidApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = VoidApiRaw(api_client)
