# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from connex_pay_python_sdk.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    API_V1_TOKEN = "/api/v1/token"
    API_V1_SALES = "/api/v1/sales"
    API_V1_VOID = "/api/v1/void"
    API_V1_RETURNS = "/api/v1/returns"
    API_V1_CANCEL = "/api/v1/cancel"
    API_V1_AUTHONLYS = "/api/v1/authonlys"
    API_V1_CAPTURES = "/api/v1/Captures"
    API_V1_VERIFY = "/api/v1/verify"
    API_V1_3DS = "/api/v1/3ds"
    API_V1_3DS_GUID = "/api/v1/3ds/{GUID}"
    API_V1_SALES_UPDATE_FUTURE_SALE = "/api/v1/sales/UpdateFutureSale"
    API_V1_SALES_ACTIVATE_SALE_GUID = "/api/v1/sales/Activate/{SaleGuid}"
    API_V1_SEARCH_SALES_EXPORTABLE_PAGE_NUMBER_PAGE_SIZE = "/api/v1/Search/Sales/{exportable}/{pageNumber}/{pageSize}"
    API_V1_SEARCH_VOIDS_EXPORTABLE_PAGE_NUMBER_PAGE_SIZE = "/api/v1/Search/Voids/{exportable}/{pageNumber}/{pageSize}"
    API_V1_SEARCH_RETURNS_EXPORTABLE_PAGE_NUMBER_PAGE_SIZE = "/api/v1/Search/Returns/{exportable}/{pageNumber}/{pageSize}"
    API_V1_SEARCH_VERIFY_EXPORTABLE_PAGE_NUMBER_PAGE_SIZE = "/api/v1/Search/Verify/{exportable}/{pageNumber}/{pageSize}"
    API_V1_HOSTED_PAYMENT_PAGE_REQUESTS = "/api/v1/HostedPaymentPageRequests"
    API_V1_MERCHANT_SELF_SERVICE_FUNDING = "/api/v1/MerchantSelfServiceFunding"
    API_V1_MERCHANT_FLEX_FUNDING_FUNDS_TRANSFER = "/api/v1/MerchantFlexFunding/Funds/Transfer"
    API_V1_ISSUE_CARD = "/api/v1/IssueCard"
    API_V1_ISSUE_CARD_ISSUE_LITE = "/api/v1/IssueCard/IssueLite"
    API_V1_ISSUE_CARD_LODGED_CARD = "/api/v1/IssueCard/LodgedCard"
    API_V1_ISSUE_CARD_CARD_GUID = "/api/v1/IssueCard/{cardGuid}"
    API_V1_ISSUE_CARD_LODGED_CARD_CARD_GUID = "/api/v1/IssueCard/LodgedCard/{CardGuid}"
    API_V1_TERMINATE_CARD_GUID = "/api/v1/TerminateCard/&lt;guid&gt;"
    API_V1_ISSUE_CARD_CANCEL_CARD_GUID = "/api/v1/IssueCard/Cancel/{{CardGuid}}"
    API_V1_ISSUE_CARD_SEND_PAYMENT_INFO_CARD_GUID = "/api/v1/IssueCard/SendPaymentInfo/{cardGuid}"
    API_V1_CARDS_CARD_GUID_SHOW_FULL_PAN = "/api/v1/Cards/{CardGuid}/{ShowFullPan}"
    API_V1_ADDENDUM_VIRTUAL_CARD = "/api/v1/Addendum/VirtualCard"
    V1_ADDENDUM_REMOVE_GUID = "/v1/Addendum/Remove/&lt;guid&gt;"
    API_V1_ISSUE_CARD_UPDATE_DELAYED_CARD_CARD_GUID = "/api/v1/IssueCard/UpdateDelayedCard/{{CardGuid}}"
    API_V1_ISSUE_CARD_ACTIVATE_DELAYED_CARD_CARD_GUID = "/api/v1/IssueCard/ActivateDelayedCard/{{CardGuid}}"
    API_V1_MERCHANTS_MERCHANT_GUID_PAYEES = "/api/v1/Merchants/{merchantGuid}/Payees"
    API_V1_MERCHANTS_MERCHANT_GUID_PAYEES_SEARCH_PAGE_PAGESIZE = "/api/v1/Merchants/{merchantGuid}/Payees/Search/{page}/{pagesize}"
    API_V1_MERCHANTS_MERCHANT_GUID_PAYEES_PAYEE_GUID = "/api/v1/Merchants/{merchantGuid}/Payees/{payeeGuid}"
    API_V1_PUSH_TO_CARD_PAYEES = "/api/v1/PushToCard/Payees"
    API_V1_PUSH_TO_CARD_PAYEES_PAYEE_GUID_STATUS = "/api/v1/PushToCard/Payees/{payeeGuid}/{status}"
    API_V1_PUSH_TO_CARD_PAYEES_PAYEE_GUID = "/api/v1/PushToCard/Payees/{payeeGuid}"
    API_V1_PUSH_TO_CARD_PAYOUTS = "/api/v1/PushToCard/Payouts"
    API_V1_PUSH_TO_CARD_PAYOUTS_PAYOUT_GUID_CANCEL = "/api/v1/PushToCard/Payouts/{payoutGuid}/Cancel"
    API_V1_PUSH_TO_CARD_PAYOUTS_PAYOUT_GUID = "/api/v1/PushToCard/Payouts/{payoutGuid}"
    API_V1_PUSH_TO_CARD_AUTHENTICATE_PAYMENT_WIDGET = "/api/v1/PushToCard/AuthenticatePaymentWidget"
    API_V1_PUSH_TO_CARD_PAYMENTS_RID_GUID_CARD_ID = "/api/v1/PushToCard/Payments/{ridGuid}/{cardId}"
    API_V1_ISSUE_ACH = "/api/v1/IssueACH"
    API_V1_ISSUE_ACH_ISSUE_LITE = "/api/v1/IssueACH/IssueLite"
    API_V1_ADDENDUM_ACH = "/api/v1/Addendum/ACH"
    API_V1_MERCHANTSUPPLIER_SETTINGS = "/api/v1/merchantsupplier/settings"
    API_V1_CARDS_TRANSACTIONS_CARD_GUID = "/api/v1/Cards/Transactions/{cardGuid}"
    API_V1_SEARCH_AVAILABLE_FUNDS_MERCHANT_GUID = "/api/v1/Search/AvailableFunds/{merchantGuid}"
    API_V1_PURCHASE_EVENT_HISTORY_RESEND = "/api/v1/PurchaseEventHistory/Resend"
    API_CHARGEBACK_GET_BY_USER = "/api/chargeback/GetByUser"
    API_V1_AUTHENTICATE = "/api/v1/authenticate"
    API_V1_ACCOUNTING_DAILY_DETAIL = "/api/v1/Accounting/DailyDetail"
    API_V1_ACCOUNTING_DAILY_SUMMARY = "/api/v1/Accounting/DailySummary"
    API_V1_SEARCH_ISSUED_CARDS = "/api/v1/Search/IssuedCards"
    API_V1_SEARCH_SETTLEMENTS = "/api/v1/Search/Settlements"
